const express = require("express")
require("dotenv").config()
const cors = require("cors")
const { sequelize } = require("./model")

const app = express()
app.use(express.json())
app.use(cors())

const PORT = process.env.PORT || 5577

sequelize
    .sync()
    .then(() => {
        console.log("DB ulandi");
        app.listen(PORT, () => {
            console.log(`Server running at http://localhost:${PORT}`);

        })
    })
    .catch((err) => console.error("DB error: ", err))

const customer = require("./routes/customer.routes")
const customerAddress = require("./routes/customerAddress.routes")
const customerCard = require("./routes/customerCard.routes")
const customerCart = require("./routes/customerCart.routes")
const booking = require("./routes/booking.routes")
const paymentMethod = require("./routes/paymentMethod.routes")
const deliveryMethod = require("./routes/deliveryMethod.routes")
const region = require("./routes/region.routes")
const district = require("./routes/district.routes")
const venue = require("./routes/venue.routes")
const lang = require("./routes/lang.routes")
const eventType = require("./routes/eventType.routes")
const category = require("./routes/humanCategory.routes")
const event = require("./routes/event.routes")
const venuePhoto = require("./routes/venuePhoto.routes")
const types = require("./routes/types.routes")
const venueTypes = require("./routes/venueTypes.routes")
const seatType = require("./routes/seatType.routes")
const seat = require("./routes/seat.routes")
const ticketStatus = require("./routes/ticketStatus.routes")
const ticket = require("./routes/ticket.routes")
const cartItem = require("./routes/cartItem.routes")

app.use("/api/customer-address", customerAddress)
app.use("/api/customer", customer)
app.use("/api/customer-card", customerCard)
app.use("/api/customer-cart", customerCart)
app.use("/api/booking", booking)
app.use("/api/payment-method", paymentMethod)
app.use("/api/delivery-method", deliveryMethod)
app.use("/api/region", region)
app.use("/api/district", district)
app.use("/api/venue", venue)
app.use("/api/lang", lang)
app.use("/api/event-type", eventType)
app.use("/api/category", category)
app.use("/api/event", event)
app.use("/api/venue-photo", venuePhoto)
app.use("/api/types", types)
app.use("/api/venue-type", venueTypes)
app.use("/api/seat-type", seatType)
app.use("/api/seat", seat)
app.use("/api/ticket-status", ticketStatus)
app.use("/api/cart-item", cartItem)
const { swaggerUi, swaggerSpec } = require("./swagger/swagger")
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec))